[line_break]
disabled = true

[package]
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
# format = " took [$duration]($style)"

[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
# format = "[$path]($style)[$lock_symbol]($lock_style) "

[nodejs]
format = "[🤖 $version](bold green) "
not_capable_style = "bold red"