[line_break]
disabled = true

[package]
disabled = true

[cmd_duration]
min_time = 10_000

[directory]
truncation_length = 10
truncate_to_repo = true

[nodejs]
format = "[🤖 $version](bold green) "
not_capable_style = "bold red"
